language: android
jdk: oraclejdk8
before_install:
 - "sudo apt-get -qq update"
 - "sudo apt-get install -y xvfb"
 - "export DISPLAY=:99.0"
 - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
 - "pushd /tmp"
 - "git clone --depth=1 https://github.com/secure-software-engineering/DroidBench.git"
 - "popd"
 - "mkdir -p $TRAVIS_BUILD_DIR/com.ibm.wala.dalvik.test/lib"
 - "find /usr/local -name dx.jar -exec cp '{}' $TRAVIS_BUILD_DIR/com.ibm.wala.dalvik.test/lib/dx.jar ';'"
install:
 - mvn clean verify -DskipTests=true -B -q
script:
 - mvn clean verify -B -q
 - ./build-maven-jars.py "install -Dgpg.skip"
sudo: false
cache:
  directories:
    - $HOME/.m2
    - $TRAVIS_BUILD_DIR/com.ibm.wala.core.testdata/ocaml/ocamljava-2.0-alpha1/lib
    
